.TH DIRMENU 1 dirmenu\-VERSION
.SH NAME
dirmenu \- directory menu
.SH SYNOPSIS
.B dirmenu
.RB [ \-bfivh ]
.RB [ \-l
.IR lines ]
.RB [ \-m
.IR monitor ]
.RB [ \-p
.IR prompt ]
.RB [ \-fn
.IR font ]
.RB [ \-nb
.IR color ]
.RB [ \-nf
.IR color ]
.RB [ \-sb
.IR color ]
.RB [ \-sf
.IR color ]
.RB [ \-db
.IR color ]
.RB [ \-df
.IR color ]
.RB [ \-w
.IR windowid ]
.RB [ \-d
.IR directory ]
.SH DESCRIPTION
.B dirmenu
is a dynamic menu for X based on 
.IR dmenu (1).
dirmenu shows the files from a directory.
When the user selects an item and presses Return, their choice is printed
to stdout and dirmenu terminates.  Entering text will narrow the items to those
matching the tokens in the input. Pressing tab will switch the directory (if a directory is highlighted).
.SH OPTIONS
.TP
.B \-b
dirmenu appears at the bottom of the screen.
.TP
.B \-f
dirmenu grabs the keyboard before reading the directory content.  This is faster, but will lock up
X until stdin reaches end\-of\-file.
.TP
.B \-i
dirmenu matches menu items case insensitively.
.TP
.B \-h
dirmenu shows hidden files.
.TP
.BI \-l " lines"
dirmenu lists items vertically, with the given number of lines.
.TP
.BI \-m " monitor"
dirmenu is displayed on the monitor number supplied. Monitor numbers are starting
from 0.
.TP
.BI \-p " prompt"
defines the prompt to be displayed to the left of the input field.
.TP
.BI \-fn " font"
defines the font or font set used.
.TP
.BI \-nb " color"
defines the normal background color.
.IR #RGB ,
.IR #RRGGBB ,
and X color names are supported.
.TP
.BI \-nf " color"
defines the normal foreground color.
.TP
.BI \-sb " color"
defines the selected background color.
.TP
.BI \-sf " color"
defines the selected foreground color.
.TP
.BI \-db " color"
defines the directory background color.
.TP
.BI \-df " color"
defines the directory foreground color.
.TP
.B \-v
prints version information to stdout, then exits.
.TP
.BI \-w " windowid"
embed into windowid.
.TP
.BI \-d " directory"
start in directory.
.SH USAGE
dirmenu is completely controlled by the keyboard.  Items are selected using the
arrow keys, page up, page down, home, and end.
.TP
.B Tab
Copy the selected item to the input field. If it is a directory, switch to that directory.
.TP
.B Return
Confirm selection.  Prints the selected item to stdout and exits, returning
success.
.TP
.B Ctrl-Return
Confirm selection.  Prints the selected item to stdout and continues.
.TP
.B Shift\-Return
Confirm input.  Prints the input text to stdout and exits, returning success.
.TP
.B Escape
Exit without selecting an item, returning failure.
.TP
C\-a
Home
.TP
C\-b
Left
.TP
C\-c
Escape
.TP
C\-d
Delete
.TP
C\-e
End
.TP
C\-f
Right
.TP
C\-g
Escape
.TP
C\-h
Backspace
.TP
C\-i
Tab
.TP
C\-j
Return
.TP
C\-J
Shift-Return
.TP
C\-k
Delete line right
.TP
C\-m
Return
.TP
C\-M
Shift-Return
.TP
C\-n
Down
.TP
C\-p
Up
.TP
C\-u
Delete line left
.TP
C\-w
Delete word left
.TP
C\-y
Paste from primary X selection
.TP
C\-Y
Paste from X clipboard
.TP
M\-g
Home
.TP
M\-G
End
.TP
M\-h
Up
.TP
M\-j
Page down
.TP
M\-k
Page up
.TP
M\-l
Down
.SH SEE ALSO
.IR dmenu (1)
